<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('indexheader'); ?>

    <!-- Header -->
    <header id="head">
        <div class="container">
            <div class="row">
                <h1 class="lead"><b>FlightTravelAir</b><br>
                    <p class="tagline">Ready for take off?</p>

            </div>
        </div>
    </header>
    <!-- /Header -->


    <!-- Intro -->
    <div class="container text-center">

        <img width="25%" height="25%">
        <h2 class="thin"></h2>
        <br>
        <h2 class="thin">Sobre a FlightTravelAir</h2>
        <br>
        <p class="text-muted">
            A FlightTravelAir foi um projeto desenvolvido no Politécnico de Leiria, no âmbito da cadeira de PWS do curso de Programação e Sistemas de Informação, cujo principal objetivo é permitir que passageiros possam efetuar a compra de uma passagem aérea de forma simples, rápida e direta.
            <br>Através da plataforma, o passageiro pode visualizar a informação relativamente aos voos e respetivas escalas e horários.
            <br>Poderá também consultar o número de pontos que possui, pontos esses que o passageiro recebe a cada 100km percorridos.
            <br>A plataforma FlightTravelAir permite também a administração e gestão de voos e toda a informação que está associada. Esta funcionalidade encontra-se disponível apenas para o administrador.
            <br>Foi também criado um Gestor de Marketing, que ficará encarregue dos desconto nos preços das escalas e dos voos.
        </p>

        <!-- Highlights - jumbotron -->
        <div class="jumbotron top-space">
            <div class="container">
                <h3 class="text-center thin">Finalidades</h3>
                <div class="row">
                    <div class="col-md-3 col-sm-6 highlight">
                        <div class="h-captionn"><h4><i class="fa fa-cogs fa-1"></i> Consultar Aeroportos</h4></div>
                        <div class="h-body text-center">
                            <p></p>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-6 highlight">
                        <div class="h-captionn"><h4><i class="fa fa-ticket fa-5"></i>Comprar Bilhes</h4></div>
                        <div class="h-body text-center">
                            <p></p>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-6 highlight">
                        <div class="h-captionn"><h4><i class="fa fa-plane fa-5"></i>Consultar Voo´s</h4></div>
                        <div class="h-body text-center">
                            <p></p>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-6 highlight">
                        <div class="h-captionn"><h4><i class="fa fa-clock-o fa-5"></i>Horários</h4></div>
                        <div class="h-body text-center">
                            <p></p>
                        </div>
                    </div>
                </div> <!-- /row  -->

            </div>
        </div>
        <!-- Intro -->
        <div class="container text-center">
            <br>
            <img width="25%" height="25%">
            <h2 class="thin"></h2>
            <br>
            <h2 class="thin">Insituto Politécnico de Leiria</h2>
            <br>
            <p class="text-muted">O Politécnico de Leiria (IPLeiria) é uma instituição pública de ensino superior</p>
            <p class="text-muted">Atualmente o Politécnico de Leiria conta com cerca de 11.500 estudantes e ministra mestrados, pós-graduações, licenciaturas, cursos técnicos superiores profissionais (TeSP) e cursos para estudantes internacionais.
                <br>
            <p class="text-muted">Este instituto promove ativamente o desenvolvimento regional, nacional e a internacionalização. Valoriza a inclusão, a cooperação, a responsabilidade, a criatividade e o espírito crítico e empreendedor.</p>
            <div class="wrapper">
                <div class="parent">
                    <div class="child bg-one">
                        <a href="https://www.ipleiria.pt/estg/" class="a-link">IPL</a>
                    </div>
                </div>

                <div class="parent right">

                    <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12272.376765602201!2d-8.8112735!3d39.737535!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x6be7f333c202b1c9!2sPolit%C3%A9cnico%20de%20Leiria!5e0!3m2!1spt-PT!2spt!4v1624913397543!5m2!1spt-PT!2spt" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>

                </div>
            </div>
        </div>
    </div>

<?php Layout::includeLayout('footer')?>