<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('adminheader') ?>
<?php $aeroporto = Data::get('aeroporto') ?>
<?php ErrMgr::attach($aeroporto) ?>

    <!-- container -->
    <div class="container">
        <div class="row">
            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">Gerir <?=$aeroporto->nome?></h1>
                </header>
                <div class="panel panel-default">
                    <div class="panel-body">
                        <hr>
                        <form class="form-horizontal" method="post" action="<?=Url::toRoute('admin/doUpdateAero', $aeroporto->id)?>">
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Nome:</label>
                                <div class="col-sm-6">
                                    <input type="text" value="<?=$aeroporto->nome?>" class="form-control" required name="nome">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Localidade:</label>
                                <div class="col-sm-6">
                                    <input type="text" required value="<?=$aeroporto->localidade?>" class="form-control" name="localidade">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">País:</label>
                                <div class="col-sm-6">
                                    <input type="text" required value="<?=$aeroporto->pais?>" class="form-control" name="pais">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Telefone:</label>
                                <div class="col-sm-6">
                                    <input type="text" required value="<?=$aeroporto->telefone?>" class="form-control" name="telefone">
                                </div>
                            </div>
                            <hr>
                            <div class="col-lg-4 text-right">
                                <button class="btn btn-default" type="submit">Editar</button>
                            </div>
                    </div>
                    </form>
                </div>
        </div>
        </article>
        <!-- /Article -->
    </div>
    </div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>