<?php use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('adminheader') ?>
<?php $aeroporto = Data::get('aeroporto')?>
<?php ErrMgr::attach($aeroporto) ?>
    <!-- container -->
    <div class="container">
        <ol class="breadcrumb">
            <li><a href="gestaoAero">Home</a></li>
            <li class="active"></li>
        </ol>
        <div class="row">
            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">Adicionar Aeroporto</h1>
                </header>
                <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <form method="post" action=<?=URL::toRoute('admin/aeroportosAdd') ?>>
                                <div class="top-margin">
                                    <label>Nome:</label>
                                    <input type="text" value="<?=$aeroporto->nome ?>" name="nome" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Localidade</label>
                                    <input type="text" value="<?=$aeroporto->localidade ?>" name="localidade" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Pais:</label>
                                    <input type="text" value="<?=$aeroporto->pais ?>" name="pais" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Telefone:</label>
                                    <input type="text" value="<?=$aeroporto->telefone?>" name="telefone" class="form-control">
                                </div>
                                <hr>
                                <div class="row">
                                    <div class="col-lg-12 text-right">
                                        <button class="button button2" style="margin-right:180px; " type="submit" onclick="msg()">Adicionar</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </article>
            <!-- /Article -->
        </div>
    </div> <!-- /container -->
<?php Layout::includeLayout('footer') ?>