<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('adminheader');
$operadores = Data::get('operador')
?>
    <!-- container -->
    <div class="container">

        <ol class="breadcrumb">
            <li><a href="index">Home</a></li>
            <li class="active">Funcionários</li>
        </ol>
        <h2 class="text-left top-space">Funcionários</h2>
        <h2 class="top-space"></h2>
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-striped"><thead><th><h3>Role:</h3></th><th><h3>Nome:</h3></th><th><h3>Localidade:</h3></th><th><h3>País:</h3></th><th><h3>Telefone:</h3></th><th><h3>Editar:</h3></th><th><h3>Apagar:</h3></th></thead>
                    <tbody>
                    <?php foreach ($operadores as $operador) { ?>
                        <tr>
                            <td><?=$operador->role?></td>
                            <td><?=$operador->nome?></td>
                            <td><?=$operador->morada?></td>
                            <td><?=$operador->email?></td>
                            <td><?=$operador->telefone?></td>
                            <td>
                                <a href="<?=Url::toRoute('admin/funcioUpdate', $operador->id)?>" class="btn btn-success" role="button">Gerir</a>
                            </td>
                            <td>
                                <a href="<?=Url::toRoute('admin/funcioEliminar', $operador->id)?>" class="btn btn-success" role="button">Apagar</a>
                            </td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>
            </div>

        </div> <!-- /row -->
        <h3>Adicionar Funcionários:</h3>
        <p>
            <a href="<?=Url::toRoute('admin/funcionarioForm')?>" class="btn btn-info" role="button">Adicionar</a>
        </p>
    </div>	<!-- /container -->

<?php Layout::includeLayout('footer')?>