<?php use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('adminheader') ?>
<?php $operador = Data::get('aeroporto')?>
<?php ErrMgr::attach($operador) ?>

    <!-- container -->
    <div class="container">

        <ol class="breadcrumb">
            <li><a href="gestaoAero" style="color: #FF9B22">Home</a></li>
            <li class="active">Adicionar Funcionários</li>
        </ol>
        <div class="row">
            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">Adicionar Funcionário</h1>
                </header>

                <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <form method="post" action=<?=URL::toRoute('admin/funcioAdd') ?>>
                                <div class="top-margin">
                                    <label>Nome:</label>
                                    <input type="text" value="<?=$operador->nome ?>" name="nome" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Morada:</label>
                                    <input type="text" value="<?=$operador->morada ?>" name="morada" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Email:</label>
                                    <input type="email" value="<?=$operador->email ?>" name="email" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Nif:</label>
                                    <input type="text" value="<?=$operador->nif?>" name="nif" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Telefone:</label>
                                    <input type="text" value="<?=$operador->telefone?>" name="telefone" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Username:</label>
                                    <input type="text" value="<?=$operador->username?>" name="username" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Password:</label>
                                    <input type="password" value="<?=$operador->password?>" name="password" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Cargo:</label>
                                    <select name="role" class="form-control" value="<?=$operador->role?>">
                                        <option value="admin">Administrador</option>
                                        <option value="gestorvoo">Gestor de Voo</option>
                                        <option value="opcheckin" >Operador de Checkin</option>
                                        <option value="opmarketing" >Operador de Marketing</option>
                                    </select>
                                </div>
                                <hr>
                                <div class="row">
                                    <div class="col-lg-12 text-right">
                                        <button class="button button2" style="margin-right:180px; " type="submit" onclick="msg()">Adicionar</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>

                </div>

            </article>
            <!-- /Article -->

        </div>
    </div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>