<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('adminheader');
?>
    <!-- container -->
    <div class="container">

        <ol class="breadcrumb">
            <li><a href="index">Home</a></li>
            <li class="active">Aeroportos</li>
        </ol>
        <div class="col-sm-6">
            <h3>Gestão Aeroportos</h3>
            <p>
                <a href="<?=Url::toRoute('admin/GestaoAero')?>" class="btn btn-info" role="button">Entrar</a>
            </p>
            <br>
            <h3>Gestão Funcionários</h3>
            <p>
                <a href="<?=Url::toRoute('admin/Funcionario')?>" class="btn btn-info" role="button">Entrar</a>
            </p>
        </div>
        </div> <!-- /row -->

    </div>	<!-- /container -->

<?php Layout::includeLayout('footer')?>