<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('clienteheader') ?>
<?php
$voos = Data::get('voos');
$aeroportos = Data::get('aeroportos');
$Voo = new Voo();
$escalas = Data::get('escalas');
?>

    <!-- container -->
    <div class="container">

        <ol class="breadcrumb">
            <li><a href="index.html">Home</a></li>
            <li class="active">Voos</li>
        </ol>

        <h2 class="text-left top-space">Voos</h2>
        <h3>Aqui poderá obter todas as informações necessárias para ter uma viagem incrível!</h3>

    </div>
    <br><br>
<?php foreach ($voos as $voo) { ?>
    <div class="card card-1" style="background-image: url(https://4.bp.blogspot.com/-3zTI9AQgTy8/XBQIDhtanFI/AAAAAAAAOe0/AXCA-TUsASY6hfoLr0T3h0TBQkox936BQCLcBGAs/s1600/AIRPLANE-WALLPAPER-TUMBLR-IPHONE-BLOG-ALINE-RIBEIRO.jpg) ;"><br><?=$voo->descricao?>
        <br><br><?=$Voo->NomeAero($aeroportos, $voo->idaeroportoorigem)?>&nbsp;-&nbsp;<?=$Voo->NomeAero($aeroportos, $voo->idaeroportodestino)?>
        <br><?=$Voo->Longitude($escalas, $voo->id) . ' milhas'?>
        <br><br> <?=$voo->preco . ' €'?><br>
        <br><br><br><br><br><br><br>
        <a href="<?=Url::toRoute('cliente/mostrar', $voo->id)?>" class="btn btn-info" role="button">Ver</a>
        <br><br>
        <a href="<?=Url::toRoute('cliente/comprar', $voo->id)?>" class="btn btn-success" role="button">Comprar</a>
    </div>
<?php } ?>

    <!-- /container -->


<?php Layout::includeLayout('footer')?>