<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('clienteheader') ?>
<?php
$voo = Data::get('voo');
$aeroportoOrigem = Data::get('aeroportoOrigem');
$aeroportoDestino = Data::get('aeroportoDestino');
$primeiraEscala = Data::get('primeiraEscala');
$ultimaEscala = Data::get('ultimaEscala');
$dataOrigemTime = strtotime($primeiraEscala->dataorigem);
$dataOrigem = date('Y-m-d', $dataOrigemTime);
?>

    <!-- container -->
    <div class="container">

        <div class="row">

            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">Voo '<?=$voo->descricao?>'</h1>
                </header>

                <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <hr>

                            <form method="post" action="<?=Url::toRoute('cliente/pagar', $voo->id)?>">
                                <div class="top-margin">
                                    <label>Aeroporto Origem <span class="text-danger">*</span></label>
                                    <input readonly="true" type="text" value="<?=$aeroportoOrigem->nome?>" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Aeroporto Destino <span class="text-danger">*</span></label>
                                    <input readonly="true" type="text" value="<?=$aeroportoDestino->nome?>" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Data ida <span class="text-danger">*</span></label>
                                    <input readonly="true" type="text" value="<?=$dataOrigem?>" name="dataida" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Preco<span class="text-danger">*</span></label>
                                    <input readonly="true" type="text" value="<?=$voo->preco?> €" name="precopago" class="form-control">
                                </div>
                                <hr>
                                <div class="col-lg-4 text-right">
                                    <button class="btn btn-action" type="submit">Pagar</button>
                                </div>
                        </div>
                        </form>
                    </div>
                </div>

        </div>

        </article>
        <!-- /Article -->

    </div>
    </div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>