<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('clienteheader'); ?>


    <!-- Header -->
    <header id="head">
        <div class="container">
            <div class="row">
                <h1 class="lead"><b>Viaje em Estilo</b><br></h1>
                <p class="tagline">Developing better Flights. Creating better Journey´s.</p>
                <p><a class="btn btn-action btn-lg" role="button" href="<?= Url::toRoute('cliente/bilhete')?>">Comprar Bilhete</a></p>
                <p class="small">By<i> FlighTravelAir</i></p>
            </div>
        </div>
    </header>
    <!-- /Header -->

    <!-- Header -->
    <header>
        <div class="container">
            <div class="row">
                <h1 class="lead"><b>Bem Vindo!</b>
                    <br><h5>Aproveite os saldos de Verão para umas boas férias.</h5><br>
                </h1>
            </div>
        </div>
    </header>
    <!-- /Header -->

    <!-- container  Aviões -->
    <div class="container">
        <h1>Não implementado de momento. :(</h1>
    </div>
    <!-- /container -->

<?php Layout::includeLayout('footer')?>