<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('clienteheader'); ?>

    <!-- Header -->
    <header>
        <div class="container">
            <div class="row">
                <h1 class="lead"><b>Bem Vindo!</b>
                    <br><h5>Aproveite os saldos de Verão para umas boas férias.</h5><br>
                </h1>
            </div>
        </div>
    </header>
    <!-- /Header -->

    <!-- container  Aviões -->
    <div class="container">
        <h1>Não implementado de momento. :(</h1>
    </div>
    <!-- /container -->

<?php Layout::includeLayout('footer')?>