<?php use

    ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('clienteheader') ?>
<?php
$voo = Data::get('voo');
$aeroporto = Data::get('aeroporto');
?>

    <!-- container -->
    <div class="container">

        <div class="row">

            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <br><br>
                <h1 class="page-title">Voo '<?=$voo->descricao?>'</h1>
                </header>
                <br><br>
                <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <hr>

                            <form method="post" action="<?=Url::toRoute('cliente/bilhete')?>">
                                <div class="top-margin">
                                    <label>Designacao <span class="text-danger">*</span></label>
                                    <input readonly="true" type="text" value="<?=$voo->descricao?>" name="designacao" class="form-control">
                                </div>

                                <div class="top-margin">
                                    <label>Custo<span class="text-danger">*</span></label>
                                    <input readonly="true" type="text" value="<?=$voo->preco?> €" name="precovenda" class="form-control">
                                </div>
                                <hr>

                                <div class="col-lg-4 text-right">
                                    <button class="btn btn-action" type="submit" style="margin-left:180px;">Voltar</button>
                                </div>
                        </div>
                        </form>
                    </div>
                </div>
            </article>

            </article>
            <!-- /Article -->

        </div>
    </div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>