<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('gestorheader');
$escala = Data::get('escala');
$aeroportos = Data::get('aeroportos');
$idvoo = Data::get('idvoo');
ErrMgr::attach($escala);
?>

    <!-- container -->
    <div class="container">
        <ol class="breadcrumb">
            <li><a href="">Home</a></li>
            <li class="active">Nova Escala</li>
        </ol>

        <div class="row">

            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">Nova Escala</h1>
                </header>

                <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <hr>
                            <form method="post" action="<?=Url::toRoute('gestorvoo/escalaAdd')?>">
                                <div>
                                    <input type="hidden" value="<?=$idvoo?>" name="idvoo">
                                </div>

                                <div class="top-margin">
                                    <label>Data de Partida: <span class="text-danger">*</span></label>
                                    <input type="date" value="<?=$escala->dataorigem?>" name="dataorigem" class="form-control">
                                    <?= ErrMgr::bind('dataorigem') ?>
                                </div>

                                <div class="top-margin">
                                    <label>Data de Chegada:</label>
                                    <input type="date" value="<?=$escala->datadestino?>" name="datadestino" class="form-control">
                                    <?= ErrMgr::bind('datadestino')?>
                                </div>
                                <div class="top-margin">
                                    <label>Distância:</label>
                                    <input type="text" value="<?=$escala->distancia?>" name="distancia" class="form-control" placeholder="Introduza a distância (distancia)">
                                    <?= ErrMgr::bind('distancia') ?>
                                </div>
                                <div class="top-margin">
                                    <label>Aeroporto de origem:</label>
                                    <?php
                                    echo('<select name="idaeroportoorigem" class="form-control">');
                                    foreach($aeroportos as $aeroporto)
                                    {
                                        echo('<option value="' . $aeroporto->id . '">' . $aeroporto->nome . '</option>');
                                    }
                                    echo('</select>');
                                    ?>
                                </div>
                                <div class="top-margin">
                                    <label>Aeroporto de destino:<span class="text-danger">*</span></label>
                                    <?php
                                    echo('<select name="idaeroportodestino" class="form-control">');
                                    foreach($aeroportos as $aeroporto)
                                    {
                                        echo('<option value="' . $aeroporto->id . '">' . $aeroporto->nome . '</option>');
                                    }
                                    echo('</select>');
                                    ?>
                                </div>
                                <input type="hidden">
                                <hr>

                                <div class="col-lg-4 text-right">
                                    <button class="btn btn-info" type="submit" style="margin-top: -10px; margin-left: 180px;">Criar</button>
                                </div>
                        </div>
                        </form>
                    </div>
                </div>

        </div>

        </article>
        <!-- /Article -->

    </div>
    </div>	<!-- /container -->

<?php Layout::includeLayout('footer')?>