<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('gestorheader');
$escala = Data::get('escala');
$aeroportos = Data::get('aeroportos');
$idvoo = Data::get('idvoo');
ErrMgr::attach($escala);
?>
    <!-- container -->
    <div class="container">
        <div class="row">
            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header>
                    <h1 class="page-title" style="color: #5bc0de;">Editar Escala</h1>
                </header>

                <hr>
                <form class="form-horizontal" method="post" style="margin-left: 240px;" action="<?=Url::toRoute('gestorvoo/doUpdateEscala', $escala->id)?>">
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="referencia">Data de Partida:</label>
                        <div class="col-sm-6">
                            <input type="date" value="<?=$escala->dataorigem?>" class="form-control" required name="dataorigem">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="tipoaviao">Data de Chegada:</label>
                        <div class="col-sm-6">
                            <input type="date" required value="<?=$escala->datadestino?>" class="form-control" name="datadestino">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="lotacao">Distância:</label>
                        <div class="col-sm-6">
                            <input type="text" required value="<?=$escala->distancia?>" class="form-control" name="distancia">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="lotacao">Custo:</label>
                        <div class="col-sm-6">
                            <input type="text" required value="<?=$escala->custo?>" class="form-control" name="custo">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="lotacao">Aeroporto de Chegada:</label>
                        <div class="col-sm-6">
                            <?php
                            echo('<select name="idaeroportodestino" class="form-control">');
                            foreach($aeroportos as $aeroporto)
                            {
                                echo('<option value="' . $aeroporto->id . '">' . $aeroporto->nome . '</option>');
                            }
                            echo('</select>');
                            ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="lotacao">Aeroporto de Chegada:</label>
                        <div class="col-sm-6">
                            <?php
                            echo('<select name="idaeroportodestino" class="form-control">');
                            foreach($aeroportos as $aeroporto)
                            {
                                echo('<option value="' . $aeroporto->id . '">' . $aeroporto->nome . '</option>');
                            }
                            echo('</select>');
                            ?>
                        </div>
                    </div>

                    <div class="col-lg-4 text-right">
                        <button class="btn btn-info" type="submit" style=" margin-top:-15px; margin-right: -160px;">Guardar</button>
                    </div>
        </div>
        </form>
    </div>
    </div>
    </article>
    <!-- /Article -->
    <!-- /container -->
<?php Layout::includeLayout('footer') ?>