<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('gestorheader') ?>
<?php

$aviao = Data::get('aviao');
?>

<!-- container -->
<div class="container">

    <ol class="breadcrumb">
        <li><a href="index">Home</a></li>
        <li class="active">Aviões</li>
    </ol>
    <div class="row">
        <div class="col-sm-12">
            <table class="table table-striped"><thead><th><h3>Referência:</h3></th><th><h3>Lotação:</h3></th></th><th><h3>Editar:</h3></th></th><th><h3>Apagar:</h3></th></thead>
                <tbody>
                <?php foreach ($aviao as $aviao) { ?>
                    <tr>
                        <td><?=$aviao->referencia?></td>
                        <td><?=$aviao->lotacao?></td>
                        <td>
                            <a href="<?=Url::toRoute('gestorvoo/aviaoUpdate', $aviao->id)?>" class="btn color-green" role="button">Gerir</a>
                        </td>
                        <td>
                            <a href="<?=Url::toRoute('gestorvoo/aviaoEliminar', $aviao->id)?>" class="btn color-red" role="button">Apagar</a>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<br>
<h3>Inserir Avião</h3>
<br>
<a href="<?=Url::toRoute('gestorvoo/getAviaoForm')?>" style="margin-top: -10px; margin-left: 15px;" class="btn btn-info" role="button">Entrar</a><svg xmlns="http://www.w3.org/2000/svg" color="grey" width="16" height="16" fill="currentColor" class="bi bi-clouds-fill" viewBox="0 0 16 16"/>

<!-- /container -->


<?php Layout::includeLayout('footer')?>
