<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('opheader'); ?>

    <!-- Header -->
    <header>
        <div class="container">
            <div class="row">
            </div>
        </div>
    </header>
    <!-- /Header -->

    <!-- container  Aviões -->
    <div class="container">

    </div>
    <!-- /container -->

<?php Layout::includeLayout('footer')?>