<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('gestorheader') ?>
<?php $voo = Data::get('voo');
$aeroportos = Data::get('aeroportos');?>
<?php ErrMgr::attach($voo) ?>


    <!-- container -->
    <div class="container">
        <div class="row">
            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">Novo Voo</h1>
                </header>
                <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <hr>
                            <form method="post" action="<?=Url::toRoute('gestorvoo/doUpdatevoos')?>">
                                <div class="top-margin">
                                    <label>Descrição:</label>
                                    <input type="text" value="<?=$voo->descricao?>" name="descricao" class="form-control"
                                    <?= ErrMgr::bind('descricao') ?>
                                </div>
                                <hr>
                                <div class="col-lg-12 text-right">
                                    <button class="button button2" style="margin-right:180px; " type="submit" onclick="msg()">Adicionar</button>
                                </div>
                        </div>
                        </form>
                    </div>
                </div>

        </div>

        </article>
        <!-- /Article -->

    </div>
    </div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>