<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('gestorheader');
$voos = Data::get('voos');
$aeroportos = Data::get('aeroportos');
$aeroportoOrigem = Data::get('aeroportoOrigem');
$aeroportoDestino = Data::get('aeroportoDestino');
$Voo = new Voo();
$escalas = Data::get('escalas');
?>


    <!-- container -->
    <div class="container">
        <div class="row">
            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">Gerir <?=$voos->descricao?></h1>
                </header>
                <div class="panel panel-default">
                    <div class="panel-body">
                        <hr>
                        <form class="form-horizontal" method="post" action="<?=Url::toRoute('admin/doUpdateAero', $voos->id)?>">
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Nome:</label>
                                <div class="col-sm-6">
                                    <input type="text" value="<?=$voos->descricao?>" class="form-control" required name="nome">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Preço:</label>
                                <div class="col-sm-6">
                                    <input type="text" required value="<?=$voos->preco?>" class="form-control" name="localidade">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Aeroporto Destino:</label>
                                <?php
                                echo('<select name="idaeroportodestino" class="form-control">');
                                foreach($aeroportos as $aeroporto)
                                {
                                    echo('<option value="' . $aeroporto->id . '">' . $aeroporto->nome . '</option>');
                                }
                                echo('</select>');
                                ?>
                            </div>
                            <div class="form-group">
                                <label>Aeroporto de destino<span class="text-danger">*</span></label>
                                <?php
                                echo('<select name="idaeroportodestino" class="form-control">');
                                foreach($aeroportos as $aeroporto)
                                {
                                    echo('<option value="' . $aeroporto->id . '">' . $aeroporto->nome . '</option>');
                                }
                                echo('</select>');
                                ?>
                            </div>
                            <input type="hidden">
                            <br>
                            <hr>
                            <div class="col-lg-4 text-right">
                                <button class="btn btn-default" type="submit">Editar</button>
                            </div>
                    </div>
                    </form>
                </div>
        </div>
        </article>
        <!-- /Article -->
    </div>
    </div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>