<?php
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('gestorheader');
$voos = Data::get('voos');
$aeroportos = Data::get('aeroportos');
$aeroportoOrigem = Data::get('aeroportoOrigem');
$aeroportoDestino = Data::get('aeroportoDestino');
$Voo = new Voo();
$escalas = Data::get('escalas');
 ?>
    <!-- container -->
    <div class="container">
        <ol class="breadcrumb">
            <li><a href="gestaoAero">Home</a></li>
            <li class="active"></li>
        </ol>
        <div class="row">
            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">Adicionar Voo</h1>
                </header>
                <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <form method="post" action=<?=URL::toRoute('admin/aeroportosAdd') ?>>
                                <div class="top-margin">
                                    <label>Nome:</label>
                                    <input type="text" value="<?=$voos->descricao ?>" name="descricao" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Localidade</label>
                                    <input type="text" value="<?=$voos->preco ?>" name="preco" class="form-control">
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-sm-2" for="name">Aeroporto Origem:</label>
                                    <select name="idaeroportoorigem" class="col-sm-6" class="form-control" value="<?=$voos->idaeroportoorigem?>">
                                        <?php foreach ($aeroportos as $aeroporto) { ?>
                                            <option value="<?=$voos->idaeroportoorigem?>"> </option>
                                        <?php } ?>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-sm-2" for="name">Aeroporto Destino:</label>
                                    <select name="idaeroportodestino" class="col-sm-6" class="form-control" value="<?=$voos->idaeroportodestino?>">
                                        <?php foreach ($aeroportos as $aeroporto) { ?>
                                            <option value="<?=$voos->idaeroportodestino?>"> </option>
                                        <?php } ?>
                                    </select>
                                </div>
                                <hr>
                                <div class="row">
                                    <div class="col-lg-12 text-right">
                                        <button class="button button2" style="margin-right:180px; " type="submit" onclick="msg()">Adicionar</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </article>
            <!-- /Article -->
        </div>
    </div> <!-- /container -->
<?php Layout::includeLayout('footer') ?>