<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('adminappheader') ?>
<?php $funcionario = Data::get('funcionario') ?>
<?php ErrMgr::attach($funcionario) ?>

    <!-- container -->
    <div class="container">

        <div class="row">

            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">A editar a informação do <?=$funcionario->role. " '" . $funcionario->nome . "'"?></h1>
                </header>


                <div class="panel panel-default">
                    <div class="panel-body">
                        <hr>
                        <form class="form-horizontal" method="post" action="<?=Url::toRoute('funcionario/update', $funcionario->id)?>">

                            <div class="form-group">
                                <label class="control-label col-sm-2" for="nome">Nome<span class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="text" value="<?=$funcionario->nome?>" class="form-control" required name="nome" placeholder="Introuza o nome">
                                    <?= ErrMgr::bind('nome') ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="role">Função<span class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="text" readonly="true" required value="<?=$funcionario->role?>" class="form-control" name="role" placeholder="Intrduza a morada">
                                    <?= ErrMgr::bind('morada') ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="morada">Morada<span class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="text" required value="<?=$funcionario->morada?>" class="form-control" name="morada" placeholder="Intrduza a morada">
                                    <?= ErrMgr::bind('morada') ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="email">Email<span class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="text" required value="<?=$funcionario->email?>" class="form-control" name="email" placeholder="Introduza o email">
                                    <?= ErrMgr::bind('email') ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="nif">NIF<span class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="text" required value="<?=$funcionario->nif?>" class="form-control" name="nif" placeholder="Introduza o NIF">
                                    <?= ErrMgr::bind('nif') ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="telefone">Telefone<span class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="text" required value="<?=$funcionario->telefone?>" class="form-control" name="telefone" placeholder="Introduza o telefone">
                                    <?= ErrMgr::bind('telefone') ?>
                                </div>
                            </div>
                            <hr>

                            <div class="col-lg-4 text-right">
                                <button class="btn btn-default" type="submit">Guardar</button>
                            </div>
                        </form>
                    </div>
                </div>



            </article>
            <!-- /Article -->

        </div>
    </div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>