<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('adminappheader') ?>
<?php $funcionarios = Data::get('funcionario') ?>

    <div class="container">

        <ol class="breadcrumb">
            <li><a href="<?=Url::toRoute('adminapp/index')?>">Home</a></li>
            <li class="active">Funcionários</li>
        </ol>

        <h2 class="text-left top-space">Lista de Funcionários</h2>
        <h2 class="top-space"></h2>
        <div class="row">
            <div class="col-sm-1-12">
                <table class="table table-striped"><thead><th><h3>Função</h3></th><th><h3>Nome</h3><th><h3>Telefone</h3></th><th><h3>Ações de Gestão</h3></th></thead>
                    <tbody>
                    <?php foreach ($funcionarios as $funcionario) { ?>
                        <tr>
                            <td><?=$funcionario->role?></td>
                            <td><?=$funcionario->nome?></td>
                            <td><?=$funcionario->telefone?></td>
                            <td>
                                <a href="<?=Url::toRoute('funcionario/show', $funcionario->id)?>" class="btn btn-info" role="button">Ver detalhes</a>
                                <a href="<?=Url::toRoute('funcionario/edit', $funcionario->id)?>" class="btn btn-warning" role="button">Editar</a>
                                <a href="<?=Url::toRoute('funcionario/destroy', $funcionario->id)?>" class="btn btn-danger" role="button">Eliminar</a>
                            </td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>

            </div>
            <div class="col-sm-6">
                <h3>Novo Funcionário</h3>
                <p>
                    <a href="<?=Url::toRoute('funcionario/create')?>" class="btn btn-info" role="button">Novo</a>
                </p>
            </div>
        </div> <!-- /row -->

    </div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>