<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Debug;

Layout::includeLayout('adminappheader') ?>
<?php $funcionario = Data::get('funcionario') ?>

    <!-- container -->
    <div class="container">

        <div class="row">

            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">Informações do <?=$funcionario->role. " '" . $funcionario->nome . "'"?></h1>
                </header>

                <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <hr>

                            <form method="post" action="<?=Url::toRoute('funcionario/index')?>">
                                <div class="top-margin">
                                    <label>Nome<span class="text-danger">*</span></label>
                                    <input readonly="true" type="text" value="<?php echo $funcionario->nome?>" name="descricao" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Função<span class="text-danger">*</span></label>
                                    <input readonly="true" type="text" value="<?=$funcionario->role?>" name="role" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Morada<span class="text-danger">*</span></label>
                                    <input readonly="true" type="text" value="<?=$funcionario->morada?>" name="morada" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Email<span class="text-danger">*</span></label>
                                    <input readonly="true" type="text" value="<?=$funcionario->email?>" name="email" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>NIF<span class="text-danger">*</span></label>
                                    <input readonly="true" type="text" value="<?=$funcionario->nif?>" name="nif" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Telefone<span class="text-danger">*</span></label>
                                    <input readonly="true" type="text" value="<?=$funcionario->telefone?>" name="telefone" class="form-control">
                                </div>
                                <hr>

                                <div class="col-lg-4 text-right">
                                    <button class="btn btn-action" type="submit">Voltar</button>
                                </div>
                        </div>
                        </form>
                    </div>
                </div>

        </div>

        </article>
        <!-- /Article -->

    </div>
    </div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>