<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('flightappheader') ?>
<?php
$voo = Data::get('voo');
$Voo = new Voo();
?>

    <!-- container -->
    <div class="container">

        <ol class="breadcrumb">
            <li><a href="index.html">Home</a></li>
            <li class="active">Escalas</li>
        </ol>

        <h2 class="text-left top-space">Escalas</h2>
        <h2 class="top-space"></h2>
        <div class="row">
            <div class="col-sm-12">
                <h1>Voo: <?=$voo->designacao?></h1>
            </div>
            <div class="col-sm-12">
                <table class="table table-striped"><thead><th><h3>Aeroporto Origem</h3></th><th><h3>Hora Origem</h3></th><th><h3>Aeroporto Destino</h3></th><th><h3>Hora Destino</h3></th><th><h3>Distância</h3></th><th><h3>Custo</h3></th><th><h3>Ver</h3></th><th><h3>Editar</h3></th><th><h3>Eliminar</h3></th></thead>
                    <tbody>
                    <?php foreach ($voo -> escalas as $escala) { ?>
                        <tr>
                            <td><?=$escala->aeroportoorigem->nome?></td>
                            <td><?=date_format($escala->dataorigem, 'd-m-Y') . ' às ' . $escala->horaorigem . ' h';?></td>
                            <td><?=$escala->aeroportodestino->nome?></td>
                            <td><?=date_format($escala->datadestino, 'd-m-Y') . ' às' . $escala->horadestino . ' h';?></td>
                            <td><?=$escala->distancia?></td>
                            <td><?=$escala->custo . ' €'?></td>
                            <td>
                                <a href="<?=Url::toRoute('escala/show', $escala->id)?>" class="btn btn-info" role="button">Ver</a>
                            </td>
                            <td>
                                <a href="<?=Url::toRoute('escala/edit', $escala->id)?>" class="btn btn-warning" role="button">Editar</a>
                            </td>
                            <td>
                                <a href="<?=Url::toRoute('escala/destroy', $escala->id)?>" class="btn btn-danger" role="button">Eliminar</a>
                            </td>
                        </tr>
                    <?php } ?>

                    </tbody>

                </table>

            </div>
            <div class="col-sm-6">
                <h3>Introduzir uma nova escala</h3>
                <p>
                    <a href="<?=Url::toRoute('escala/create', $voo->id)?>" class="btn btn-info" role="button">Criar</a>
                </p>
            </div>
            <div class="col-sm-6">
                <h3>Voltar a voos</h3>
                <p>
                    <a href="<?=Url::toRoute('voo/index')?>" class="btn btn-success" role="button">Voltar</a>
                </p>
            </div>
        </div> <!-- /row -->

    </div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>