<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('opheader') ?>
<?php $voo = Data::get('voo')?>
<?php ErrMgr::attach($voo) ?>


    <!-- container -->
    <div class="container">

        <div class="row">

            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">Novo Voo</h1>
                </header>

                <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <hr>
                            <form method="post" action="<?=Url::toRoute('voo/store')?>">
                                <div class="top-margin">
                                    <label>Designação <span class="text-danger">*</span></label>
                                    <input type="text" value="<?=$voo->designacao?>" name="designacao" class="form-control" placeholder="Introduza a descrição do voo">
                                    <?= ErrMgr::bind('designacao') ?>
                                </div>
                                <hr>

                                <div class="col-lg-4 text-right">
                                    <button class="btn btn-action" type="submit">Criar</button>
                                </div>
                        </div>
                        </form>
                    </div>
                </div>

        </div>

        </article>
        <!-- /Article -->

    </div>
    </div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>