<?php use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('indexheader') ?>
    <br>
    <br>
    <br>
    <br>
    <br>

    <!-- container -->
    <div class="container">

        <ol class="breadcrumb">
            <li><a href="../../../middleware/frontcontroller.php">Home</a></li>
            <li class="active">User access</li>
        </ol>

        <div class="row">

            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">Sign in</h1>
                </header>

                <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <h3 class="thin text-center">Entrar na sua conta</h3>
                            <p class="text-center text-muted">Caso não tenha conta registe-se <a href="<?=URL::toRoute('login/registration')?>">aqui</a>.</p>
                            <hr>

                            <form method="post" action="<?= URL::toRoute('login/dologin')?>">
                                <div class="top-margin">
                                    <label>Username <span class="text-danger">*</span></label>
                                    <input type="text" name="username" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Password <span class="text-danger">*</span></label>
                                    <input type="password" name="password" class="form-control">
                                </div>

                                <hr>

                                <div class="row">

                                    <div class="col-lg-12 text-right">
                                        <button class="btn btn-action" type="submit">Sign in</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>

                </div>

            </article>
            <!-- /Article -->

        </div>
    </div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>