<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('opheader'); ?>
    <!-- Header -->
    <header id="head">
        <div class="container">
            <div class="row">
                <h1 class="lead"><b>Viaje em Estilo</b><br></h1>
                <p class="tagline">Wherever you go, we go with you</p>

                <p class="small">By<i> FlighTravelAir</i></p>
            </div>
        </div>
    </header>
    <li class="card">
        <a class="card-image" target="_blank" style="background-image: url(https://images5.alphacoders.com/863/863248.jpg);">

        </a>
        <a class="card-description" style="text-decoration: none">
            <h5>Gestão de Discontos</h5>
            <a href="<?=Url::toRoute('opmarketing/gestaoDisconto')?>" style="margin-top: -10px; margin-left: 15px;" class="btn btn-info" role="button">Entrar</a><svg xmlns="http://www.w3.org/2000/svg" color="grey" width="16" height="16" fill="currentColor" class="bi bi-clouds-fill" viewBox="0 0 16 16">
        </a>
        </a>
    </li>
    <br>
<?php Layout::includeLayout('footer')?>