<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('opheader'); ?>
    <!-- Header -->
    <header id="head">
        <div class="container">
            <div class="row">
                <h1 class="lead"><b>Viaje em Estilo</b><br></h1>
                <p class="tagline">Wherever you go, we go with you</p>

                <p class="small">By<i> FlighTravelAir</i></p>
            </div>
        </div>
    </header>
    <br>
<?php Layout::includeLayout('footer')?>