<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>

    <!-- Header -->
    </header>
    <li class="card">
        <a class="card-image" target="_blank" style="background-image: url(https://media-manager.noticiasaominuto.com/1920/naom_5da427611729f.jpg);">

        </a>
        <a class="card-description" style="text-decoration: none">
            <h5>Gestão de Discontos</h5>
            <a href="<?=Url::toRoute('opmarketing/gestaoDisconto')?>" style="margin-top: -10px; margin-left: 15px;" class="btn color-orange-1" role="button">Entrar</a><svg xmlns="http://www.w3.org/2000/svg" color="grey" width="16" height="16" fill="currentColor" class="bi bi-clouds-fill" viewBox="0 0 16 16">
        </a>
        </a>
    </li>
    <br>
<?php Layout::includeLayout('footer')?>